# Dependabot configuration for GitHub Actions
# This will automatically create PRs to update GitHub Actions to their latest versions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh-actions-packages:
        patterns:
          - "*"
