stages:
  - info
  - lint
  - test

# In this configuration:
# - "high" refers to the macOS version bringing the latest Xcode tooling
# - "low" refers to the macOS version bringing the oldest supported Xcode tooling

ENV info (high):
  stage: info
  tags:
    - macos:ventura
    - specific:true
  allow_failure: true # do not block GH PRs
  script:
    - ./tools/gitlab/env_info.sh

ENV info (low):
  stage: info
  tags:
    - macos:sonoma
    - specific:true
  allow_failure: true # do not block GH PRs
  script:
    - ./tools/gitlab/env_info.sh

Lint:
  stage: lint
  tags:
    - mac-ventura-preview
  allow_failure: true # do not block GH PRs
  script:
    - ./tools/lint/run-linter.sh
    - ./tools/license/check-license.sh

SDK unit tests (iOS):
  stage: test
  tags:
    - mac-ventura-preview
  allow_failure: true # do not block GH PRs
  variables:
    TEST_WORKSPACE: "Datadog.xcworkspace"
    TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.0.1"
  script:
    - make dependencies-gitlab
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogCoreTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogInternalTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogLogsTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogTraceTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogRUMTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore iOS" -only-testing:"DatadogWebViewTrackingTests iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogSessionReplay iOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCrashReporting iOS" test | xcbeautify

SDK unit tests (tvOS):
  stage: test
  tags:
    - mac-ventura-preview
  allow_failure: true # do not block GH PRs
  variables:
    TEST_WORKSPACE: "Datadog.xcworkspace"
    TEST_DESTINATION: "platform=tvOS Simulator,name=Apple TV,OS=17.0"
  script:
    - make dependencies-gitlab
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore tvOS" -only-testing:"DatadogCoreTests tvOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore tvOS" -only-testing:"DatadogInternalTests tvOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore tvOS" -only-testing:"DatadogLogsTests tvOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore tvOS" -only-testing:"DatadogTraceTests tvOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCore tvOS" -only-testing:"DatadogRUMTests tvOS" test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "DatadogCrashReporting tvOS" test | xcbeautify

SDK integration tests (iOS):
  stage: test
  tags:
    - mac-ventura-preview
  allow_failure: true # do not block GH PRs
  variables:
    TEST_WORKSPACE: "IntegrationTests/IntegrationTests.xcworkspace"
    TEST_DESTINATION: "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.0.1"
  script:
    - make dependencies-gitlab
    - make prepare-integration-tests
    # Before running crash reporting tests, disable Apple Crash Reporter so it doesn't capture the crash causing tests hang on "<app> quit unexpectedly" prompt:
    - launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
    - ./tools/config/generate-http-server-mock-config.sh
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "IntegrationScenarios" -testPlan DatadogIntegrationTests test | xcbeautify
    - xcodebuild -workspace "$TEST_WORKSPACE" -destination "$TEST_DESTINATION" -scheme "IntegrationScenarios" -testPlan DatadogCrashReportingIntegrationTests test | xcbeautify
