stages:
  - .pre
  - tools
  - lint
  - test

tools versions:
  stage: .pre
  tags:
    - mac-ventura-preview
  script:
    - system_profiler SPSoftwareDataType
    - python3 -V
    - curl --version
    - wget --version
    - gcc --version
    - cmake --version
    - xcodebuild -version
    - jq --version
    - gh --version
    - aws --version
    - bundler --version
    - node --version
    - yarn --version
    - swiftlint --version
    - carthage version
    - brew -v

# swift tools:
#   stage: tools
#   tags:
#     - mac-ventura-preview
#   script: 
#     - swift test --package-path instrumented-tests/http-server-mock
#     - swift test --package-path tools/rum-models-generator
#     - swift test --package-path tools/sr-snapshots

# python tools:
#   stage: tools
#   tags:
#     - mac-ventura-preview
#   script:
#     - |
#       cd tools/distribution && make
#       venv/bin/python3 -m pytest tests
#     - |
#       cd tools/nightly-unit-tests && make
#       venv/bin/python3 -m pytest tests

lint:
  stage: lint
  tags:
    - mac-ventura-preview
  script:
    - ./tools/lint/run-linter.sh
    - ./tools/license/check-license.sh

unit test:
  stage: test
  tags:
    - mac-ventura-preview
  script:
    - brew install xcbeautify
    - carthage bootstrap --platform iOS,tvOS --use-xcframeworks
    - xcodebuild -workspace Datadog.xcworkspace -scheme "DatadogCore iOS" -showdestinations
    - make source-xcconfigs
    - xcodebuild -workspace Datadog.xcworkspace -scheme "DatadogCore iOS" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' test | xcbeautify
