stages:
  - pre
  - lint
  - test
  - ui-test

# Default configuration for all jobs:
default:
  tags:
    - macos:sonoma
    - specific:true

# Utility job that conditions when to add inheriting jobs to the pipeline:
.run:on-sdk-changes:
  rules:
    - changes:
        - "Datadog*/**/*"
        - "IntegrationTests/**/*"
        - "TestUtilities/**/*"
        - "*.yml"

ENV check:
  stage: pre
  script:
    - ./tools/runner-setup.sh --ios # temporary, waiting for AMI
    - make env-check

Lint:
  stage: lint
  script:
    - ./tools/runner-setup.sh --ios # temporary, waiting for AMI
    - make clean repo-setup ENV=ci
    - make lint license-check
    - make rum-models-verify sr-models-verify

Unit Tests (iOS):
  stage: test
  extends: .run:on-sdk-changes
  variables:
    OS: "latest"
    PLATFORM: "iOS Simulator"
    DEVICE: "iPhone 15 Pro"
  script:
    - ./tools/runner-setup.sh --ios # temporary, waiting for AMI
    - make clean repo-setup ENV=ci
    - make test-ios-all OS="$OS" PLATFORM="$PLATFORM" DEVICE="$DEVICE"

Unit Tests (tvOS):
  stage: test
  extends: .run:on-sdk-changes
  variables:
    OS: "latest"
    PLATFORM: "tvOS Simulator"
    DEVICE: "Apple TV"
  script:
    - ./tools/runner-setup.sh --tvos # temporary, waiting for AMI
    - make clean repo-setup ENV=ci
    - make test-tvos-all OS="$OS" PLATFORM="$PLATFORM" DEVICE="$DEVICE"

UI Tests:
  stage: ui-test
  extends: .run:on-sdk-changes
  variables:
    OS: "latest"
    PLATFORM: "iOS Simulator"
    DEVICE: "iPhone 15 Pro"
  parallel:
    matrix:
      - TEST_PLAN:
          - Default
          - RUM
          - CrashReporting
          - NetworkInstrumentation
  script:
    - ./tools/runner-setup.sh --ios # temporary, waiting for AMI
    - make clean repo-setup ENV=ci
    - make ui-test TEST_PLAN="$TEST_PLAN" OS="$OS" PLATFORM="$PLATFORM" DEVICE="$DEVICE"
