version: 1
builder:
  configs:
    - platform: ios
      documentation_targets: ["DatadogInternal", "DatadogCore", "DatadogLogs", "DatadogTrace", "DatadogRUM", "DatadogSessionReplay", "DatadogCrashReporting", "DatadogWebViewTracking"]