issuer: https://gitlab.ddbuild.io

subject_pattern: "project_path:DataDog/dd-sdk-ios:ref_type:tag:ref:refs/tags/.*"

claim_pattern:
  project_path: "DataDog/dd-sdk-ios"
  ref_type: "tag"
  ref_protected: "true"
  pipeline_source: "push"
  ci_config_ref_uri: "gitlab.ddbuild.io/DataDog/dd-sdk-ios//.gitlab-ci.yml@refs/heads/master"

permissions:
  contents: write
